site_url : https://asalvadorc.github.io/BBDD
site_name: AD - Access a Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png
nav:
  - Tema 1-Sistema de fitxers: https://asalvadorc.github.io/AD_Tema1
  - Tema 2-Model Gestió del contingut de fitxers: https://asalvadorc.github.io/AD_Tema2
  - Tema 3-Fitxers de diferents formats: https://asalvadorc.github.io/AD_Tema3

